# Generated by Django 2.0.6 on 2018-08-22 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180822_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12, verbose_name='评论的用户')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('date_publish', models.DateField(auto_now_add=True, verbose_name='评论时间')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='comment_set',
        ),
        migrations.AddField(
            model_name='comment',
            name='article_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Article', verbose_name='评论的对象文章'),
        ),
        migrations.AddField(
            model_name='comment',
            name='cmt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Comment', verbose_name='父评论'),
        ),
    ]
