# Generated by Django 2.0.6 on 2018-08-24 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180822_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='cmt',
            new_name='parent_cmt',
        ),
    ]
